In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv("../Files/titanic.csv")
df.head()

   survived  pclass  gender   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [3]:
selected_columns = ["survived","pclass","gender","age","sibsp","parch","embarked"]
df = df[selected_columns]

In [4]:
x = df.drop("survived",axis=1)
y = df["survived"]

In [5]:
categorical_features = ["pclass","gender","sibsp","parch","embarked"]
encoder = OneHotEncoder(sparse_output=False,handle_unknown='ignore')

In [6]:
encoded_data = encoder.fit_transform(df[categorical_features])
feature_name = encoder.get_feature_names_out(categorical_features)

In [7]:

encoded_df = pd.DataFrame(encoded_data,columns=feature_name)

In [8]:
missing_value_age = x["age"].isna().isna().any()
if missing_value_age:
    print("Handling nulls....")
    imputer = SimpleImputer(strategy="mean")
    imputer.fit(x["age"])
    x["age"] =imputer.transform(x[["age"]])[:,0]

print(x.age)

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [10]:
scaler = StandardScaler()
scaler.fit(x[["age"]])
x_scaled = x.copy()

In [11]:
print(x_scaled)

     pclass  gender   age  sibsp  parch embarked
0         3    male  22.0      1      0        S
1         1  female  38.0      1      0        C
2         3  female  26.0      0      0        S
3         1  female  35.0      1      0        S
4         3    male  35.0      0      0        S
..      ...     ...   ...    ...    ...      ...
886       2    male  27.0      0      0        S
887       1  female  19.0      0      0        S
888       3  female   NaN      1      2        S
889       1    male  26.0      0      0        C
890       3    male  32.0      0      0        Q

[891 rows x 6 columns]

In [12]:
x_scaled.loc[:,"age"] = scaler.transform(x[["age"]])

In [13]:
print(x_scaled)

     pclass  gender       age  sibsp  parch embarked
0         3    male -0.530377      1      0        S
1         1  female  0.571831      1      0        C
2         3  female -0.254825      0      0        S
3         1  female  0.365167      1      0        S
4         3    male  0.365167      0      0        S
..      ...     ...       ...    ...    ...      ...
886       2    male -0.185937      0      0        S
887       1  female -0.737041      0      0        S
888       3  female       NaN      1      2        S
889       1    male -0.254825      0      0        C
890       3    male  0.158503      0      0        Q

[891 rows x 6 columns]

In [14]:
df_merged = pd.concat([encoded_df,x_scaled["age"]],axis=1)

In [16]:
df_merged.head()

,pclass_1,pclass_2,pclass_3,gender_female,gender_male,sibsp_0,sibsp_1,sibsp_2,sibsp_3,sibsp_4,...,parch_2,parch_3,parch_4,parch_5,parch_6,embarked_C,embarked_Q,embarked_S,embarked_nan,age
0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.530377
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.571831
2,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.254825
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.365167
4,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.365167