In [113]:
import numpy as np
import pandas as pd

In [114]:
np.random.seed(101)
scores = np.random.randint(0,101,(4,3))
print(scores)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]

In [115]:
players = ["Virat","Rohit","MS Dhoni","KL Rahul"]
matches = ["Match 1","Match 2","Match 3"]
print(pd.DataFrame(data=scores))

df = pd.DataFrame(data=scores,index=players,columns=matches)
print(df)

    0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63
          Match 1  Match 2  Match 3
Virat          95       11       81
Rohit          70       63       87
MS Dhoni       75        9       77
KL Rahul       40        4       63

In [116]:
companies = pd.DataFrame({
    "Company":["TCS","Infosys","Wipro"],
    "Sales":[100,200,300],
    "Profit":[20,50,70]
})

print(companies)

   Company  Sales  Profit
0      TCS    100      20
1  Infosys    200      50
2    Wipro    300      70

In [117]:
# Properties of DF
print(df.shape)
print(df.head())
print(df.columns)
print(df.index)
print(df.dtypes)
df.info()

(4, 3)
          Match 1  Match 2  Match 3
Virat          95       11       81
Rohit          70       63       87
MS Dhoni       75        9       77
KL Rahul       40        4       63
Index(['Match 1', 'Match 2', 'Match 3'], dtype='str')
Index(['Virat', 'Rohit', 'MS Dhoni', 'KL Rahul'], dtype='str')
Match 1    int32
Match 2    int32
Match 3    int32
dtype: object
<class 'pandas.DataFrame'>
Index: 4 entries, Virat to KL Rahul
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Match 1  4 non-null      int32
 1   Match 2  4 non-null      int32
 2   Match 3  4 non-null      int32
dtypes: int32(3)
memory usage: 106.0 bytes

In [118]:
print(type(df["Match 1"]))

<class 'pandas.Series'>

In [119]:
df = pd.read_csv("../Files/tips.csv")

In [120]:
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296070e+15,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506810e+15,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672

In [121]:
df.head()

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251

In [122]:
len(df)

244

In [123]:
df.columns.tolist()

['total_bill',
 'tip',
 'gender',
 'smoker',
 'day',
 'time',
 'size',
 'price_per_person',
 'Payer Name',
 'CC Number',
 'Payment ID']

In [124]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563495e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040732e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525320e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596450e+15

In [125]:
df["day"].unique()

<ArrowStringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [126]:
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [127]:
df.isnull().sum()

total_bill          0
tip                 0
gender              0
smoker              0
day                 0
time                0
size                0
price_per_person    0
Payer Name          0
CC Number           0
Payment ID          0
dtype: int64

In [128]:
df.duplicated().sum()

np.int64(0)

In [129]:
summary = df.groupby("day")["tip"].mean().round(2)
summary.to_csv("tips_average_by_day.csv")

In [130]:
df.isnull().sum()

total_bill          0
tip                 0
gender              0
smoker              0
day                 0
time                0
size                0
price_per_person    0
Payer Name          0
CC Number           0
Payment ID          0
dtype: int64

In [131]:
print(df[['total_bill', 'tip']])
print(df.tip.head())

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]
0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [132]:
print("Highest bill:",  df['total_bill'].max())
print(df.loc[df['total_bill'].idxmax()])
print(df.loc[df['total_bill'].idxmin()])

Highest bill: 50.81
total_bill                       50.81
tip                               10.0
gender                            Male
smoker                             Yes
day                                Sat
time                            Dinner
size                                 3
price_per_person                 16.94
Payer Name               Gregory Clark
CC Number           5473850000000000.0
Payment ID                     Sat1954
Name: 170, dtype: object
total_bill                        3.07
tip                                1.0
gender                          Female
smoker                             Yes
day                                Sat
time                            Dinner
size                                 1
price_per_person                  3.07
Payer Name               Tiffany Brock
CC Number           4359490000000000.0
Payment ID                     Sat3455
Name: 67, dtype: object

In [133]:
df.iloc[0, df.columns.get_loc('tip')] = 1.50
df.loc[df['size'] > 5, 'time'] = 'Dinner'

In [134]:
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.50,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296070e+15,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506810e+15,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672

In [135]:
df.loc[df['size'] >= 5, ['size', 'time']]

     size    time
125     6  Dinner
141     6  Dinner
142     5   Lunch
143     6  Dinner
155     5  Dinner
156     6  Dinner
185     5  Dinner
187     5  Dinner
216     5  Dinner

In [136]:
df['tip_%'] = (100*df['tip']/df['total_bill']).round(2)
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_%
0,16.99,1.50,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959,8.83
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.296070e+15,Sat2657,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.506810e+15,Sat1766,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.011890e+15,Sat3880,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.375220e+12,Sat17,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.511450e+15,Thur672,15.97

In [137]:
df['price_per_person'] = (df['total_bill']/df['size'])
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_%
0,16.99,1.50,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6.011810e+15,Sun4458,16.66
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.98
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.68
...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5.296070e+15,Sat2657,20.39
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3.506810e+15,Sat1766,7.36
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6.011890e+15,Sat3880,8.82
242,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82
243,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97

In [138]:
print(df['total_bill'] > 30)
print(df[df['total_bill'] > 30])

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool
     total_bill    tip  gender smoker   day    time  size  price_per_person  \
11        35.26   5.00  Female     No   Sun  Dinner     4          8.815000
23        39.42   7.58    Male     No   Sat  Dinner     4          9.855000
39        31.27   5.00    Male     No   Sat  Dinner     3         10.423333
44        30.40   5.60    Male     No   Sun  Dinner     4          7.600000
47        32.40   6.00    Male     No   Sun  Dinner     4          8.100000
52        34.81   5.20  Female     No   Sun  Dinner     4          8.702500
56        38.01   3.00    Male    Yes   Sat  Dinner     4          9.502500
59        48.27   6.73    Male     No   Sat  Dinner     4         12.067500
83        32.68   5.00    Male    Yes  Thur   Lunch     2         16.340000
85        34.83   5.17  Female     No  Thur   Lunch     4          8.707500
95        40.17   4.73    Male    Yes   Fri  Dinner     4         10.042500
102       44.30   2.50  Female    Yes   Sat  Dinner     3         14.766667
112       38.07   4.00    Male     No   Sun  Dinner     3         12.690000
141       34.30   6.70    Male     No  Thur  Dinner     6          5.716667
142       41.19   5.00    Male     No  Thur   Lunch     5          8.238000
156       48.17   5.00    Male     No   Sun  Dinner     6          8.028333
167       31.71   4.50    Male     No   Sun  Dinner     4          7.927500
170       50.81  10.00    Male    Yes   Sat  Dinner     3         16.936667
173       31.85   3.18    Male    Yes   Sun  Dinner     2         15.925000
175       32.90   3.11    Male    Yes   Sun  Dinner     2         16.450000
179       34.63   3.55    Male    Yes   Sun  Dinner     2         17.315000
180       34.65   3.68    Male    Yes   Sun  Dinner     4          8.662500
182       45.35   3.50    Male    Yes   Sun  Dinner     3         15.116667
184       40.55   3.00    Male    Yes   Sun  Dinner     2         20.275000
187       30.46   2.00    Male    Yes   Sun  Dinner     5          6.092000
197       43.11   5.00  Female    Yes  Thur   Lunch     4         10.777500
207       38.73   3.00    Male    Yes   Sat  Dinner     4          9.682500
210       30.06   2.00    Male    Yes   Sat  Dinner     3         10.020000
212       48.33   9.00    Male     No   Sat  Dinner     4         12.082500
219       30.14   3.09  Female    Yes   Sat  Dinner     4          7.535000
237       32.83   1.17    Male    Yes   Sat  Dinner     2         16.415000
238       35.83   4.67  Female     No   Sat  Dinner     3         11.943333

                Payer Name     CC Number Payment ID  tip_%
11            Diane Macias  4.577820e+15    Sun6686  14.18
23          Lance Peterson  3.542580e+15     Sat239  19.23
39       Mr. Brandon Berry  6.011530e+15    Sat6373  15.99
44             Todd Cooper  5.038470e+11    Sun2274  18.42
47            James Barnes  3.552000e+15    Sun9677  18.52
52            Emily Daniel  4.291280e+15    Sun6165  14.94
56   James Christensen DDS  3.497940e+14    Sat8903   7.89
59             Brian Ortiz  6.596450e+15    Sat8139  13.94
83           Daniel Murphy  5.356180e+15   Thur8801  15.30
85             Shawna Cook  6.011790e+15   Thur7972  14.84
95           Aaron Bentley  1.800270e+14    Fri9628  11.77
102          Heather Cohen  3.797710e+14    Sat6240   5.64
112             Jeff Lopez  3.572870e+15     Sun591  10.51
141         Steven Carlson  3.526520e+15   Thur1025  19.53
142           Eric Andrews  4.356530e+15   Thur3621  12.14
156          Ryan Gonzales  3.523150e+15    Sun7518  10.38
167         Michael Lawson  3.566290e+15    Sun3719  14.19
170          Gregory Clark  5.473850e+15    Sat1954  19.68
173            Scott Perez  3.577120e+15    Sun9335   9.98
175        Nathan Reynolds  3.703070e+14    Sun5109   9.45
179           Brian Bailey  3.466560e+14    Sun9851  10.25
180       James Hebert DDS  6.761690e+11    Sun7544  10.62
182           Jose Parsons  4.112210e+15    Sun2337   7.72
184            Stephen Cox  3.547800e+15    Sun5140   7.40
187          David Barrett  4.792880e+15    Sun9987   6.57
197            Brooke Soto  5.544900e+15   Thur9313  11.60
207          Ricky Ramirez  3.478180e+14    Sat4505   7.75
210          Shawn Mendoza  3.018400e+13    Sat8361   6.65
212        Alex Williamson  6.762190e+11    Sat4590  18.62
219           Shelby House  5.020970e+11    Sat8863  10.25
237           Thomas Brown  4.284720e+15    Sat2929   3.56
238         Kimberly Crane  6.761840e+11    Sat9777  13.03

In [139]:
df[['total_bill','tip','size','tip_%','price_per_person']].head()

   total_bill   tip  size  tip_%  price_per_person
0       16.99  1.50     2   8.83          8.495000
1       10.34  1.66     3  16.05          3.446667
2       21.01  3.50     3  16.66          7.003333
3       23.68  3.31     2  13.98         11.840000
4       24.59  3.61     4  14.68          6.147500

In [140]:
df['big_tipper'] = np.where(df['tip_%']>20,'Yes','No')

In [141]:
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_%,big_tipper
0,16.99,1.50,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6.011810e+15,Sun4458,16.66,No
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.98,No
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.68,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5.296070e+15,Sat2657,20.39,Yes
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3.506810e+15,Sat1766,7.36,No
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6.011890e+15,Sat3880,8.82,No
242,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No
243,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No

In [142]:
df['bill_category']=np.select(
    [df['total_bill']<10,df['total_bill']<30],
    ['$','$$'],default='$$$')

In [143]:
df

,total_bill,tip,gender,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6.011810e+15,Sun4458,16.66,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.98,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.68,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5.296070e+15,Sat2657,20.39,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3.506810e+15,Sat1766,7.36,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6.011890e+15,Sat3880,8.82,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [144]:
df[['total_bill','bill_category']]

     total_bill bill_category
0         16.99            $$
1         10.34            $$
2         21.01            $$
3         23.68            $$
4         24.59            $$
..          ...           ...
239       29.03            $$
240       27.18            $$
241       22.67            $$
242       17.82            $$
243       18.78            $$

[244 rows x 2 columns]

In [145]:
df = df.rename(columns={'total_bill':'bill','Payer Name':'payer name'})
df

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6.011810e+15,Sun4458,16.66,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.98,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.68,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.676667,Michael Avila,5.296070e+15,Sat2657,20.39,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.590000,Monica Sanders,3.506810e+15,Sat1766,7.36,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.335000,Keith Wong,6.011890e+15,Sat3880,8.82,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [146]:
df['size']=df['size'].astype(float)
df

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3.0,7.003333,Travis Walters,6.011810e+15,Sun4458,16.66,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2.0,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.98,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4.0,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.68,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3.0,9.676667,Michael Avila,5.296070e+15,Sat2657,20.39,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2.0,13.590000,Monica Sanders,3.506810e+15,Sat1766,7.36,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2.0,11.335000,Keith Wong,6.011890e+15,Sat3880,8.82,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [147]:
df['day']=df['day'].astype('category')
df

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
2,21.01,3.50,Male,No,Sun,Dinner,3.0,7.003333,Travis Walters,6.011810e+15,Sun4458,16.66,No,$$
3,23.68,3.31,Male,No,Sun,Dinner,2.0,11.840000,Nathaniel Harris,4.676140e+15,Sun5260,13.98,No,$$
4,24.59,3.61,Female,No,Sun,Dinner,4.0,6.147500,Tonya Carter,4.832730e+15,Sun2251,14.68,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3.0,9.676667,Michael Avila,5.296070e+15,Sat2657,20.39,Yes,$$
240,27.18,2.00,Female,Yes,Sat,Dinner,2.0,13.590000,Monica Sanders,3.506810e+15,Sat1766,7.36,No,$$
241,22.67,2.00,Male,Yes,Sat,Dinner,2.0,11.335000,Keith Wong,6.011890e+15,Sat3880,8.82,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [148]:
df.dtypes

bill                 float64
tip                  float64
gender                   str
smoker                   str
day                 category
time                     str
size                 float64
price_per_person     float64
payer name               str
CC Number            float64
Payment ID               str
tip_%                float64
big_tipper               str
bill_category            str
dtype: object

In [149]:
raw = pd.Series(['10','20','abc',None,'7.5'])
raw

0     10
1     20
2    abc
3    NaN
4    7.5
dtype: str

In [150]:
print(pd.to_numeric(raw, errors='coerce'))

0    10.0
1    20.0
2     NaN
3     NaN
4     7.5
dtype: float64

In [151]:
raw = pd.Series(['10','20','abc',None,'7.5'])
pd.to_numeric(raw,errors='coerce').fillna(0).astype(int)

0    10
1    20
2     0
3     0
4     7
dtype: int64

In [152]:
df['bill']>30

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: bill, Length: 244, dtype: bool

In [153]:
df[df['bill']>30]

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
11,35.26,5.00,Female,No,Sun,Dinner,4.0,8.815000,Diane Macias,4.577820e+15,Sun6686,14.18,No,$$$
23,39.42,7.58,Male,No,Sat,Dinner,4.0,9.855000,Lance Peterson,3.542580e+15,Sat239,19.23,No,$$$
39,31.27,5.00,Male,No,Sat,Dinner,3.0,10.423333,Mr. Brandon Berry,6.011530e+15,Sat6373,15.99,No,$$$
44,30.40,5.60,Male,No,Sun,Dinner,4.0,7.600000,Todd Cooper,5.038470e+11,Sun2274,18.42,No,$$$
47,32.40,6.00,Male,No,Sun,Dinner,4.0,8.100000,James Barnes,3.552000e+15,Sun9677,18.52,No,$$$
52,34.81,5.20,Female,No,Sun,Dinner,4.0,8.702500,Emily Daniel,4.291280e+15,Sun6165,14.94,No,$$$
56,38.01,3.00,Male,Yes,Sat,Dinner,4.0,9.502500,James Christensen DDS,3.497940e+14,Sat8903,7.89,No,$$$
59,48.27,6.73,Male,No,Sat,Dinner,4.0,12.067500,Brian Ortiz,6.596450e+15,Sat8139,13.94,No,$$$
83,32.68,5.00,Male,Yes,Thur,Lunch,2.0,16.340000,Daniel Murphy,5.356180e+15,Thur8801,15.30,No,$$$
85,34.83,5.17,Female,No,Thur,Lunch,4.0,8.707500,Shawna Cook,6.011790e+15,Thur7972,14.84,No,$$$
95,40.17,4.73,Male,Yes,Fri,Dinner,4.0,10.042500,Aaron Bentley,1.800270e+14,Fri9628,11.77,No,$$$
102,44.30,2.50,Female,Yes,Sat,Dinner,3.0,14.766667,Heather Cohen,3.797710e+14,Sat6240,5.64,No,$$$
112,38.07,4.00,Male,No,Sun,Dinner,3.0,12.690000,Jeff Lopez,3.572870e+15,Sun591,10.51,No,$$$
141,34.30,6.70,Male,No,Thur,Dinner,6.0,5.716667,Steven Carlson,3.526520e+15,Thur1025,19.53,No,$$$
142,41.19,5.00,Male,No,Thur,Lunch,5.0,8.238000,Eric Andrews,4.356530e+15,Thur3621,12.14,No,$$$
156,48.17,5.00,Male,No,Sun,Dinner,6.0,8.028333,Ryan Gonzales,3.523150e+15,Sun7518,10.38,No,$$$
167,31.71,4.50,Male,No,Sun,Dinner,4.0,7.927500,Michael Lawson,3.566290e+15,Sun3719,14.19,No,$$$
170,50.81,10.00,Male,Yes,Sat,Dinner,3.0,16.936667,Gregory Clark,5.473850e+15,Sat1954,19.68,No,$$$
173,31.85,3.18,Male,Yes,Sun,Dinner,2.0,15.925000,Scott Perez,3.577120e+15,Sun9335,9.98,No,$$$
175,32.90,3.11,Male,Yes,Sun,Dinner,2.0,16.450000,Nathan Reynolds,3.703070e+14,Sun5109,9.45,No,$$$
179,34.63,3.55,Male,Yes,Sun,Dinner,2.0,17.315000,Brian Bailey,3.466560e+14,Sun9851,10.25,No,$$$
180,34.65,3.68,Male,Yes,Sun,Dinner,4.0,8.662500,James Hebert DDS,6.761690e+11,Sun7544,10.62,No,$$$
182,45.35,3.50,Male,Yes,Sun,Dinner,3.0,15.116667,Jose Parsons,4.112210e+15,Sun2337,7.72,No,$$$
184,40.55,3.00,Male,Yes,Sun,Dinner,2.0,20.275000,Stephen Cox,3.547800e+15,Sun5140,7.40,No,$$$
187,30.46,2.00,Male,Yes,Sun,Dinner,5.0,6.092000,David Barrett,4.792880e+15,Sun9987,6.57,No,$$$
197,43.11,5.00,Female,Yes,Thur,Lunch,4.0,10.777500,Brooke Soto,5.544900e+15,Thur9313,11.60,No,$$$
207,38.73,3.00,Male,Yes,Sat,Dinner,4.0,9.682500,Ricky Ramirez,3.478180e+14,Sat4505,7.75,No,$$$
210,30.06,2.00,Male,Yes,Sat,Dinner,3.0,10.020000,Shawn Mendoza,3.018400e+13,Sat8361,6.65,No,$$$
212,48.33,9.00,Male,No,Sat,Dinner,4.0,12.082500,Alex Williamson,6.762190e+11,Sat4590,18.62,No,$$$
219,30.14,3.09,Female,Yes,Sat,Dinner,4.0,7.535000,Shelby House,5.020970e+11,Sat8863,10.25,No,$$$
237,32.83,1.17,Male,Yes,Sat,Dinner,2.0,16.415000,Thomas Brown,4.284720e+15,Sat2929,3.56,No,$$$
238,35.83,4.67,Female,No,Sat,Dinner,3.0,11.943333,Kimberly Crane,6.761840e+11,Sat9777,13.03,No,$$$

In [ ]:
df[(df['bill']>30) & ~(df['sex']=='Male')]

In [ ]:
df[(df['bill']>30) & (df['sex']=='Male')]

In [ ]:
#Membership and ranges
df[df['day'].isin(['Sat','Sun'])].shape

(163, 14)

In [ ]:
df[df['bill'].between(10,20)]

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,7.520000,Joseph Mcdonald,3.522870e+15,Sun6820,13.03,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,7.390000,Jerome Abbott,3.532120e+15,Sun3775,21.85,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,5.135000,William Riley,5.662880e+11,Sun2546,16.65,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,7.765000,Tracy Douglas,4.097940e+15,Sat7220,19.32,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,5.035000,Sean Gonzalez,3.534020e+15,Sat4615,12.41,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,6.300000,Matthew Myers,3.543680e+15,Sat5032,7.94,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [ ]:
df[df['bill'].between(10,20, inclusive='left')]

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,7.520000,Joseph Mcdonald,3.522870e+15,Sun6820,13.03,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,7.390000,Jerome Abbott,3.532120e+15,Sun3775,21.85,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,5.135000,William Riley,5.662880e+11,Sun2546,16.65,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,7.765000,Tracy Douglas,4.097940e+15,Sat7220,19.32,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,5.035000,Sean Gonzalez,3.534020e+15,Sat4615,12.41,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,6.300000,Matthew Myers,3.543680e+15,Sat5032,7.94,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [ ]:
df[df['bill'].between(10,20, inclusive='right')]

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,7.520000,Joseph Mcdonald,3.522870e+15,Sun6820,13.03,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,7.390000,Jerome Abbott,3.532120e+15,Sun3775,21.85,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,5.135000,William Riley,5.662880e+11,Sun2546,16.65,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,7.765000,Tracy Douglas,4.097940e+15,Sat7220,19.32,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,5.035000,Sean Gonzalez,3.534020e+15,Sat4615,12.41,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,6.300000,Matthew Myers,3.543680e+15,Sat5032,7.94,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$

In [ ]:
df[df['bill'].between(10,20, inclusive='neither')]

,bill,tip,gender,smoker,day,time,size,price_per_person,payer name,CC Number,Payment ID,tip_%,big_tipper,bill_category
0,16.99,1.50,Female,No,Sun,Dinner,2.0,8.495000,Christy Cunningham,3.560330e+15,Sun2959,8.83,No,$$
1,10.34,1.66,Male,No,Sun,Dinner,3.0,3.446667,Douglas Tucker,4.478070e+15,Sun4608,16.05,No,$$
8,15.04,1.96,Male,No,Sun,Dinner,2.0,7.520000,Joseph Mcdonald,3.522870e+15,Sun6820,13.03,No,$$
9,14.78,3.23,Male,No,Sun,Dinner,2.0,7.390000,Jerome Abbott,3.532120e+15,Sun3775,21.85,Yes,$$
10,10.27,1.71,Male,No,Sun,Dinner,2.0,5.135000,William Riley,5.662880e+11,Sun2546,16.65,No,$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,15.53,3.00,Male,Yes,Sat,Dinner,2.0,7.765000,Tracy Douglas,4.097940e+15,Sat7220,19.32,No,$$
235,10.07,1.25,Male,No,Sat,Dinner,2.0,5.035000,Sean Gonzalez,3.534020e+15,Sat4615,12.41,No,$$
236,12.60,1.00,Male,Yes,Sat,Dinner,2.0,6.300000,Matthew Myers,3.543680e+15,Sat5032,7.94,No,$$
242,17.82,1.75,Male,No,Sat,Dinner,2.0,8.910000,Dennis Dixon,4.375220e+12,Sat17,9.82,No,$$
243,18.78,3.00,Female,No,Thur,Dinner,2.0,9.390000,Michelle Hardin,3.511450e+15,Thur672,15.97,No,$$